#
#
language: minimal

os: linux
dist: trusty

branches:
  only:
  - gh-pages
  - /.*/

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file:
    - emacs/japanese_texis/*.texi*
    - emacs/japanese_texis/*.tex
    - lispref/japanese_texis/*.texi*
    - lispref/japanese_texis/*.tex    
  skip_cleanup: true
  on:
    tags: true
  
before_install:
  sudo apt-get install -y gettext;
  sudo apt-get install -y po4a;
  sudo apt-get install -y libintl-perl;
  sudo apt-get install -y realpath;
  sudo apt-get install -y texinfo;
  
install:
  make all;
  make -C emacs/japanese_texis/ -f Makefile.example info;
  make -C lispref/japanese_texis/ -f Makefile.example info;
  
