# Examples generate various documento format from texi. 
DOCUMENT := emacs
JA_SUFFIX := -ja

# for creating one entire html.
single-html: $(DOCUMENT)$(JA_SUFFIX).html
$(DOCUMENT)$(JA_SUFFIX).html: $(DOCUMENT)$(JA_SUFFIX).texi
	texi2any --set-customization-variable TEXI2HTML=1 $(DOCUMENT)$(JA_SUFFIX).texi

# for creating separated htmls in html/ directory.
multi-html: html/index.html
html/index.html: $(DOCUMENT)$(JA_SUFFIX).texi
	makeinfo -o html/ --html $(DOCUMENT)$(JA_SUFFIX).texi

# for creating one entire info.
info: $(DOCUMENT)$(JA_SUFFIX).info
$(DOCUMENT)$(JA_SUFFIX).info: $(DOCUMENT)$(JA_SUFFIX).texi
	makeinfo --no-split -o $(DOCUMENT)$(JA_SUFFIX).info $(DOCUMENT)$(JA_SUFFIX).texi

# for creating one pdf.
pdf: $(DOCUMENT)$(JA_SUFFIX).pdf
$(DOCUMENT)$(JA_SUFFIX).pdf: $(DOCUMENT)$(JA_SUFFIX).texi
	TEX=ptex texi2dvi --dvi $(DOCUMENT)$(JA_SUFFIX).texi && \
	dvipdfmx $(DOCUMENT)$(JA_SUFFIX).dvi && \
	rm -f $(DOCUMENT)$(JA_SUFFIX).dvi
