# Examples generate various documento format from texi. 
DOCUMENT := elisp
JA_SUFFIX := -ja

# for creating one entire html.
single-html: $(DOCUMENT)$(JA_SUFFIX).html
$(DOCUMENT)$(JA_SUFFIX).html: $(DOCUMENT)$(JA_SUFFIX).texi
	texi2any --document-language=ja --set-customization-variable TEXI2HTML=1 $(DOCUMENT)$(JA_SUFFIX).texi

# for creating separated htmls in html/ directory.
multi-html: html/index.html
html/index.html: $(DOCUMENT)$(JA_SUFFIX).texi
	makeinfo --document-language=ja -o html/ --html $(DOCUMENT)$(JA_SUFFIX).texi

# for creating one entire info.
info: $(DOCUMENT)$(JA_SUFFIX).info
$(DOCUMENT)$(JA_SUFFIX).info: $(DOCUMENT)$(JA_SUFFIX).texi
	makeinfo --document-language=ja --no-split -o $(DOCUMENT)$(JA_SUFFIX).info $(DOCUMENT)$(JA_SUFFIX).texi

# for creating one pdf.
pdf: $(DOCUMENT)$(JA_SUFFIX).pdf
$(DOCUMENT)$(JA_SUFFIX).pdf: $(DOCUMENT)$(JA_SUFFIX).texi
	TEX=ptex texi2dvi --dvi $(DOCUMENT)$(JA_SUFFIX).texi && \
	dvipdfmx $(DOCUMENT)$(JA_SUFFIX).dvi && \
	rm -f $(DOCUMENT)$(JA_SUFFIX).dvi

# for creating one epub(>=texinfo 7.0).
epub: $(DOCUMENT)$(JA_SUFFIX).epub
$(DOCUMENT)$(JA_SUFFIX).epub: $(DOCUMENT)$(JA_SUFFIX).texi
	makeinfo --epub3 --document-language=ja -o $(DOCUMENT)$(JA_SUFFIX).epub $(DOCUMENT)$(JA_SUFFIX).texi
