name: make-webpages-for-checking
on:
  workflow_call:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - secrets: inherit
      - run: |
          sudo apt-get install -y texinfo
          ./update_pages_for_checking.sh
