name: make-webpages-for-checking
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y gettext
      - run: sudo apt-get install -y po4a
      - run: sudo apt-get install -y libintl-perl
      - run: sudo apt-get install -y coreutils
      - run: sudo apt-get install -y texinfo
      - run: make all
      - run: ./update_pages_for_checking.sh
    
