name: make-webpages-for-checking
on: [workflow_call, workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    secrets: inherit
    env:
      API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y texinfo
      - run: ./update_pages_for_checking.sh
    
