name: make-webpages-for-checking
on:
  workflow_call:
    secrets:
      API_GITHUB_TOKEN:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          sudo apt-get install -y texinfo
      - name: run shell
        run: |
          ./update_pages_for_checking.sh
