name: make-webpages-for-checking
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: |
          sudo apt-get install -y texinfo
      - name: run shell
        run: |
          API_GITHUB_TOKEN="${{ secrets.API_GITHUB_TOKEN }}" ./update_pages_for_checking.sh
