name: make-webpages-for-checking
on:
  workflow_call:
jobs:
  main:
    secrets: inherit
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y texinfo
      - run: ./update_pages_for_checking.sh
    
