name: make-webpages-for-checking
on:
  workflow_call:
    secrets:
      API_GITHUB_TOKEN:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: run shell
        run: |
          API_GITHUB_TOKEN="${{ secrets.API_GITHUB_TOKEN }}" ./update_pages_for_checking.sh
