name: make-webpages-for-checking
on:
  workflow_call:
jobs:
  main:
    secrets:
      API_GITHUB_TOKEN:
        required: true
    env:
      API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y texinfo
      - run: ./update_pages_for_checking.sh
    
